### ISSUE TITLE
이메일 인증 api 개발

### ISSUE THREAD

**Issue by maark1106** [buddy-ya/be#1]
## 📄 설명
서비스 회원가입과 별도로 대학생만 이용할 수 있도록 대학생 인증 api를 개발합니다.
- 한국인 학생 학교 이메일 인증

---

## ✅ TO-DO-LIST
- [x] 학생 기본 Entity 생성
- [x] 이메일로 인증 코드 발송하는 기능
- [x] 받은 인증 코드를 보내 사용자 검증하는 기능

---

## 고민해볼 점

---
