### ISSUE TITLE
회원 핸드폰 번호 인증

### ISSUE THREAD

**Issue by sangu1026** [buddy-ya/be#2]
## 📄 설명
**기능 설명** 
:  SOLAPI API를 활용하여 지정 핸드폰으로 인증번호를 보내고
해당 인증번호를 우리 앱에 입력했을때 인증 완료 되는 기능 구현

**전화 번호 인증 후**
- 기존 회원일 경우 기존 회원임을 알리고 access토큰과, refresh토큰을 발급한다.
- 신규 회원일 경우 신규 회원임을 응답한다.
---

## ✅ TO-DO-LIST
- [x] 인증 코드 6자리를 랜덤으로 생성
- [x] SOLAPI API를 사용하여 인증코드를 전송
- [x] 핸드폰 번호와 인증코드를 받아 인증코드를 검증하는 서비스
- [x] 신규회원/기존회원을 구분하는 서비스
- [x] 문자 전송에 실패했을 때 전송 오류 처리
- [x] 문자 코드가 일치하지 않을 때 오류 처리
- [ ] 테스트 코드 작성

---

## 고민해볼 점
- 만약 유저가 비정상적인 요청을 했을 때 어떻게 처리 할 것 인가
- 요금 지불 방식 알아보기 (후불? 충전?)

---

## 🙋🏻 참고 자료
- [SOLAPI 가격 정책](https://solapi.com/pricing/)
- [SOLAPI API 사용법](https://nurigo.github.io/java-sdk/nurigo.sdk/net.nurigo.sdk.message.response/-single-message-sent-response/index.html)
