### ISSUE TITLE
관리자는 학생증 인증 승인, 혹은 반려

### ISSUE THREAD

**Issue by maark1106** [buddy-ya/be#21]
## 📄 설명
관리자는 재학생 인증을 위해 보낸 학생증 사진 목록을 조회합니다
해당 학생증을 확인 후 조건에 부합한다면 승인, 부합하지 않다면 반려합니다

---

## ✅ TO-DO-LIST
- [x] 학생 한 명이 사진을 2번 보낼 경우 기존 사진 없애고 최신 사진으로 업데이트 되는 기능
- [x] 학생증 목록 조회 기능
- [x] 인증이 완료되면 인증 상태 바꿔주기, S3에서 사진 삭제
- [x] 인증 거부됐다면 S3에서 사진만 삭제

---

## 고민해볼 점

---
