### ISSUE TITLE
Firebase를 활용한 알림 기능 구현 -> Expo Notification를 활용한 알림 기능 구현으로 변경

### ISSUE THREAD

**Issue by sangu1026** [buddy-ya/be#24]
### 알림 과정
![image](https://github.com/user-attachments/assets/15db813d-e06d-4276-a62e-2f8d9b46287c)

1. Client에서 기기 로그인시 Firebase 측에 FCM 토큰 발급 요청
2. Client -> Server로 FCM 토큰 저장 요청
3. 사용자가 알림이 필요한 기능 사용
4. Client -> Server로 해당 기능 API 호출 (알림 생성 요청이 포함)
5. Server는 FCM서버로부터 accessToken 발급
6. 발급받은 accessToken과 관련 키 값 및 보내려는 메시지의 데이터를 FCM 서버에 알람 요청하기
7. FCM 서버는 Server로부터 받은 값이 올바른지 확인 후 Client에게 푸시 알림 보내기

---

## ✅ TO-DO-LIST
- [x] FCM 토큰 저장 API 구현
- [ ] 상황에 따른 FCM 토큰 관리(삭제/업데이트) 로직 구현
- [x] 푸시메세지 발급 요청 구현
---

### 1. 클라이언트는 언제 토큰을 발급 받고 삭제 및 재발급 해야하는가?
- 로그인 시 발급해주면 된다.
- FCM 토큰 자체에는 명확한 만료 기간이 설정되어 있지 않으며, 일반적으로는 지속적으로 유효합니다.
따라서 만료로 인한 재발급은 구현할 필요가 없어 보인다.

### 2. 유저가 알림을 받고 싶지 않을때는 FCM 토큰을 받지 않아야 할까?
-> 토큰은 항상 발급받고, 사용자의 알림 수신 여부는 기기 또는 앱 설정을 통해 관리합니다.
- 토큰 관리 로직이 훨씬 간단
- 사용자가 언제든지 알림 설정을 변경할 수 있는 유연성 제공
- 사용자 설정 변경 시 서버로 알림 수신 여부를 업데이트해서 알림을 전송하지 않으면 됨

### 3. 재로그인시 FCM 토큰을 어떻게 할 것 인가?
서버는 해당 계정에 토큰을 업데이트하거나 새 토큰으로 덮어씁니다.

### 4. 로그 아웃시 FCM 토큰을 어떻게 할 것 인가?
토큰을 삭제합니다.

### 5. 앱을 삭제할 경우 FCM 토큰을 어떻게 할 것인가? 
앱을 삭제할 경우 해당 FCM 토큰은 무효화되지만 서버가 즉각적으로는 인지하지 못합니다. 
만약에 해당 FCM토큰(삭제된 기기)으로 알림을 전송하려고 하면 FCM 서버는
- "NotRegistered": 앱이 삭제되었거나, 토큰이 더 이상 유효하지 않은 경우 반환됩니다.
- "InvalidRegistration": 잘못된 FCM 토큰일 경우 반환됩니다.
와 같은 에러를 반환합니다. 따라서 서버가 FCM 서버에 알림 요청을 보낼 때 해당 에러가 발생할 시
서버 데이터베이스에서 삭제하거나 비활성화 하면 될 것 같습니다.
➕ 추가적으로 주기적으로 서버에서 모든 저장된 FCM 토큰으로 "더미 알림"을 전송해서 유효하지 않은
토큰을 제거하는 방식도 있다고 합니다.

### 6.  한 기기에서 여러 계정을 사용할 때는 어떻게 처리할 것인가?
한 기기에서 여러 계정을 사용(친구계정으로 로그인을 하거나, 서브 계정으로 로그인하는 경우)하는
경우에는 사용자가 로그아웃 과정을 거치기 때문에 로그아웃시 해당 계정의 FCM 토큰을 삭제하면
한 기기안에서 중복으로 푸시메세지가 발행되는 문제를 해결할 수 있을 것이다.

### 7. 여러 기기에서 한 계정을 사용할 때는 어떻게 처리할 것인가(중복 로그인)?
한사용자가 폰, 태블릿, 노트북 등의 기기에서 한 계정을 동시에 사용하려고 하는 경우 저희는
한 기기만 허용하는 것으로 정하였기에 다음과 같은 흐름을 따를려고 합니다.
1. 새 기기에서 로그인하면, 서버는 이전 기기의 FCM 토큰을 식별
2.  해당 FCM 토큰으로 "중복 접속으로 로그 아웃되었음" 푸시 알림을 전송
3.  이전 기기에서 로그아웃(FCM 토큰 삭제)
4. 해당 계정의 FCM 토큰을 새로운 기기로 등록

### 8. 이외의 예기치 않은 FCM 토큰 오류는 어떻게 처리할 것인가?
- 사용중에 예기치않게 프론트에서 FCM 토큰이 재발급되는 경우
- 의도치않게 서버에 이상한 FCM 토큰이 저장되는 경우등

이런 상황에서 저희는 Firebase로 부터 FirebaseMessagingException을 
받을텐데 메시지에 따라 오류처리가 필요해 보입니다.
![image](https://github.com/user-attachments/assets/12b90eca-59b8-4ed0-99d5-34989c72078c)

### 추후에 추가되어야 할 기능
-  한 사용자가 오랫동안 사용하지 않으면 어떻게 할 것 인가?
FCM 토큰이 테이블에 쌓이게 되면 이후에 FCM 토큰 조회시에 성능이 저하될수 있음
->  최종 사용 시각이 2달이 지난 사용자는 자동으로 로그아웃(토큰 삭제)

---

## 🙋🏻 참고 자료
**백엔드 구현 관련**
https://c-king.tistory.com/604
https://tioon.tistory.com/197
https://adjh54.tistory.com/432

[RestTemplate 사용법](https://adjh54.tistory.com/234)
[Jackson 모듈 활용하기 - 객체 JSON으로 직렬화 ](https://adjh54.tistory.com/375)
