### ISSUE TITLE
재학생 인증 부분 기능 추가

### ISSUE THREAD

**Issue by maark1106** [buddy-ya/be#26]
## 📄 설명
사용자가 자신이 제출한 학생증을 확인하는 기능 추가
이메일 인증 중복 처리

---

## ✅ TO-DO-LIST

- [ ] 자신이 제출한 학생증 확인하는 기능
- [ ] 인증 여부 api에 학생증을 보낸 상태인지 알려주는 필드 추가
- [ ] Student에 email 필드 추가 후 중복 사용자인지 검사

---

## 고민해볼 점

---
