### ISSUE TITLE
온보딩 기능

### ISSUE THREAD

**Issue by sangu1026** [buddy-ya/be#3]
## 📄 설명
- 회원 정보 입력 후 프론트가 회원 정보 저장 api를 호출하면 회원 정보를 저장하고
정상적인 저장 혹은 오류를 알린다.
- **기존 회원**일 경우 전화 번호 인증 후 바로 access토큰과, refresh토큰을 발급한다.
- **신규 회원**일 경우 전화 번호 인증 후 온보딩 과정 후 access토큰과, refresh토큰을 발급한다.

---

## ✅ TO-DO-LIST
이슈 안에서 해야할 일을 체크박스 형태로 작성해주세요.
- [x] 회원 정보 저장 API 명세서 작성
- [x] 로컬 DataBase 연동
- [x] 필요한 엔티티 정의
- [x] 회원 정보 저장 기능 구현

---

## 고민해볼 점
- 만약에 저장하지 못하고 오류가 났다면 프론트에게 어떤 응답을 줄 것인가

---
