### ISSUE TITLE
학생 프로필 추가

### ISSUE THREAD

**Issue by sangu1026** [buddy-ya/be#35]
## 📄 설명
- 온보딩에서 기본 프로필 이미지((현재 6개) 중에 **랜덤으로** 학생의 프로필 이미지 설정
- 마이페이지에서 프로필을 다른 기본 프로필 이미지 중 변경 API
- 추후에 기본 프로필 이외에 개인 프로필을 쓰는 것에 대비해 별도의 프로필 이미지 테이블(profile_image) 생성

---

## ✅ TO-DO-LIST
- [x] 프로필 테이블 생성
- [x] 기본 프로필 수정 API
- [x] 필요한 기능에 프로필 추가

---

## 고민해볼 점

---
