### ISSUE TITLE
개발 준비 내용을 확정

### ISSUE THREAD

**Issue by maark1106** [buddy-ya/be#4]
## 📄 설명
개발 준비 내용을 정리하여, 개발에 필요한 기준 및 자료를 확정하고 만듭니다

---

## ✅ TO-DO-LIST

- [x] 협업 방식 정리
- [x] 이슈 템플릿 작성
- [x] 커밋 컨벤션 작성
- [x] PR 컨벤션 및 리뷰 컨벤션 작성
- [x] 코드 컨벤션 작성
- [x] 패키지 구조 확정

---

## 고민해볼 점

---

## 🙋🏻 참고 자료
[관련 노션 링크](http://thinkable-durian-178.notion.site)
